### ISSUE TITLE
Error from Exchange when increasing the getAllAppointments() range

### ISSUE THREAD

**Issue by insanum** [gdenning/exchange-sync#16]
In SyncCalendarsImpl.java, I tried increasing the sync data range using:

```
final DateTime startDate = now.withHourOfDay(0).withMinuteOfHour(0).withSecondOfMinute(0).minusMonths(1)
final DateTime endDate = startDate.plusMonths(3);
```

And this fails with the following exception:

```
2015-10-07 13:33:16,162 ERROR c.z.exchangesync.sync.SyncCalendarsImpl - Problem synchronizing appointments - sync aborted
microsoft.exchange.webservices.data.ServiceObjectPropertyException: You must load or assign this property before you can read its value.
        at microsoft.exchange.webservices.data.PropertyBag.getPropertyValueOrException(Unknown Source) ~[exchangesync-1.0.2-jar-with-dependencies.jar:na]
        at microsoft.exchange.webservices.data.PropertyBag.getObjectFromPropertyDefinition(Unknown Source) ~[exchangesync-1.0.2-jar-with-dependencies.jar:na]
        at microsoft.exchange.webservices.data.Appointment.getStart(Unknown Source) ~[exchangesync-1.0.2-jar-with-dependencies.jar:na]
        at com.zerodes.exchangesync.exchange.ExchangeSourceImpl.getAllAppointments(ExchangeSourceImpl.java:391) ~[exchangesync-1.0.2-jar-with-dependencies.jar:na]
        at com.zerodes.exchangesync.sync.SyncCalendarsImpl.generatePairs(SyncCalendarsImpl.java:38) ~[exchangesync-1.0.2-jar-with-dependencies.jar:na]
        at com.zerodes.exchangesync.sync.SyncCalendarsImpl.syncAll(SyncCalendarsImpl.java:83) ~[exchangesync-1.0.2-jar-with-dependencies.jar:na]
        at com.zerodes.exchangesync.App.main(App.java:38) [exchangesync-1.0.2-jar-with-dependencies.jar:na]
```

While I won't begin to understand what Exchange is complaining about, I have confirmed that the range CANNOT be more than a span of two months. So minusMonths(1) to plusMonths(2) works just fine as does minusMonths(0) to plusMonths(2).

I would like to stretch out the sync upwards of 6 months from the current date.

**Comment by gdenning** [comment]
I've added a new setting called appointmentMonthsToExport which allows you to specify how many months in the future to export appointments for. Let me know if you encounter any issues!
