### ISSUE TITLE
Error on Exchange 2007

### ISSUE THREAD

**Issue by freeman512** [gdenning/exchange-sync#17]
I try to run this command on my exchange 2007 SP1 and i got this error : 

```

INFOS: NTLM authentication scheme selected
2016-02-19 11:38:19,040 ERROR c.z.exchangesync.sync.SyncCalendarsImpl - Problem synchronizing appointments - sync aborted
microsoft.exchange.webservices.data.ServiceObjectPropertyException: This property was requested, but it wasn't returned by the server.
    at microsoft.exchange.webservices.data.PropertyBag.getPropertyValueOrException(Unknown Source) ~[exchangesync-1.0.3-jar-with-dependencies.jar:na]
    at microsoft.exchange.webservices.data.PropertyBag.getObjectFromPropertyDefinition(Unknown Source) ~[exchangesync-1.0.3-jar-with-dependencies.jar:na]
    at microsoft.exchange.webservices.data.Item.getReminderMinutesBeforeStart(Unknown Source) ~[exchangesync-1.0.3-jar-with-dependencies.jar:na]
    at com.zerodes.exchangesync.exchange.ExchangeSourceImpl.convertToAppointmentDto(ExchangeSourceImpl.java:226) ~[exchangesync-1.0.3-jar-with-dependencies.jar:na]
    at com.zerodes.exchangesync.exchange.ExchangeSourceImpl.getAllAppointments(ExchangeSourceImpl.java:394) ~[exchangesync-1.0.3-jar-with-dependencies.jar:na]
    at com.zerodes.exchangesync.sync.SyncCalendarsImpl.generatePairs(SyncCalendarsImpl.java:36) ~[exchangesync-1.0.3-jar-with-dependencies.jar:na]
    at com.zerodes.exchangesync.sync.SyncCalendarsImpl.syncAll(SyncCalendarsImpl.java:81) ~[exchangesync-1.0.3-jar-with-dependencies.jar:na]
    at com.zerodes.exchangesync.App.main(App.java:38) [exchangesync-1.0.3-jar-with-dependencies.jar:na]
2016-02-19 11:38:19,041 INFO c.z.exchangesync.StatisticsCollector - Appointments added/updated/deleted: 0/0/0
2016-02-19 11:38:19,041 INFO c.z.exchangesync.StatisticsCollector - Tasks added/updated/deleted: 0/0/0
```

Any idea ?

**Comment by gdenning** [comment]
That's very odd.  Unfortunately, I don't have an Exchange 2007 SP1 server to test with, so I can't reproduce your issue.  However, I just pushed a change this weekend to upgrade the Exchange Web Services client library, so perhaps that fixed the issue. If you're able to build from source, then give it a try. Otherwise, I'll be creating a new release in a few days which you can try.

**Comment by gdenning** [comment]
I've released a new version. Let me know if you still have problems with Exchange 2007 SP1 or if it's okay now.

**Comment by gdenning** [comment]
Closing for now due to lack of response.
