### ISSUE TITLE
NullPointerException when syncing.

### ISSUE THREAD

**Issue by jhojgaard** [gdenning/exchange-sync#20]
Hi,

I started seeing a NullPointerException, when i load from Google calendar.
The error is below - but is there any way to tell which event is giving this error?

`2017-04-06 10:05:00,717 INFO c.z.e.c.google.GoogleCalendarSourceImpl - Retrieving Google Calendar events page 4
2017-04-06 10:05:00,986 ERROR c.z.exchangesync.sync.SyncCalendarsImpl - Problem synchronizing appointments - sync aborted
java.lang.NullPointerException: null
	at com.zerodes.exchangesync.calendarsource.google.GoogleCalendarSourceImpl.convertToAppointmentDto(GoogleCalendarSourceImpl.java:150) ~[exchangesync-1.0.4-jar-with-dependencies.jar:na]
	at com.zerodes.exchangesync.calendarsource.google.GoogleCalendarSourceImpl.getAllAppointments(GoogleCalendarSourceImpl.java:131) ~[exchangesync-1.0.4-jar-with-dependencies.jar:na]
	at com.zerodes.exchangesync.sync.SyncCalendarsImpl.generatePairs(SyncCalendarsImpl.java:35) ~[exchangesync-1.0.4-jar-with-dependencies.jar:na]
	at com.zerodes.exchangesync.sync.SyncCalendarsImpl.syncAll(SyncCalendarsImpl.java:81) ~[exchangesync-1.0.4-jar-with-dependencies.jar:na]
	at com.zerodes.exchangesync.App.main(App.java:39) [exchangesync-1.0.4-jar-with-dependencies.jar:na]
`

**Comment by gdenning** [comment]
Hmm, interesting. I've never seen that before. It appears that the extended properties or private extended properties of the event are missing. I've made a small change to do an extra null check in that area. Let me know if that fixes the issue for you. (You'll need to get the latest code and recompile.)

**Comment by jhojgaard** [comment]
That works, thank you.
