### ISSUE TITLE
How to reconnect to Google?

### ISSUE THREAD

**Issue by MatthiasLohr** [gdenning/exchange-sync#25]
Hello,

at some point, my OAuth token at Google got invalid, so i have to reauth exchange-sync with my Google Account. But how can i achieve that? Currently, i get the following error message:

```
2018-01-22 08:56:21,720 INFO c.z.e.exchange.ExchangeSourceImpl - Connected to Exchange.
2018-01-22 08:56:21,741 INFO c.z.e.c.google.GoogleCalendarSourceImpl - Connecting to Google Calendar...
2018-01-22 08:56:22,148 ERROR com.zerodes.exchangesync.App - An unexpected exception occurred
com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
  "error" : "invalid_grant"
}
	at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:570) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.zerodes.exchangesync.calendarsource.google.GoogleCalendarSourceImpl.getCalendarId(GoogleCalendarSourceImpl.java:120) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.zerodes.exchangesync.calendarsource.google.GoogleCalendarSourceImpl.<init>(GoogleCalendarSourceImpl.java:98) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
	at com.zerodes.exchangesync.App.main(App.java:44) ~[exchangesync-1.0.7-jar-with-dependencies.jar:na]
```

Maybe this should also be added to the documentation.

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
Ok, i just found the solution: Deleting ```~/.credentials/exchange_sync_calendar/StoredCredential``` will bring the authentication dialog back. But maybe you should introduce an app parameter like ```--google-reauth```.
