### ISSUE TITLE
Java exception when trying to sync

### ISSUE THREAD

**Issue by sereeth** [gdenning/exchange-sync#29]
It works :)

2018-11-21 15:58:15,347 INFO c.z.e.exchange.ExchangeSourceImpl - Connected to Exchange.
2018-11-21 15:58:15,376 INFO c.z.e.c.google.GoogleCalendarSourceImpl - Connecting to Google Calendar...
2018-11-21 15:58:16,273 INFO c.z.e.c.google.GoogleCalendarSourceImpl - Connected to Google Calendar.
2018-11-21 15:58:16,274 INFO c.z.exchangesync.sync.SyncCalendarsImpl - Synchronizing calendars...
2018-11-21 15:58:16,297 INFO c.z.e.c.google.GoogleCalendarSourceImpl - Retrieving Google Calendar events page 1
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/ws/http/HTTPException
	at microsoft.exchange.webservices.data.core.ExchangeService.findItems(ExchangeService.java:976)
	at microsoft.exchange.webservices.data.core.ExchangeService.findAppointments(ExchangeService.java:1264)
	at microsoft.exchange.webservices.data.core.ExchangeService.findAppointments(ExchangeService.java:1285)
	at com.zerodes.exchangesync.exchange.ExchangeSourceImpl.getAllAppointments(ExchangeSourceImpl.java:399)
	at com.zerodes.exchangesync.sync.SyncCalendarsImpl.generatePairs(SyncCalendarsImpl.java:45)
	at com.zerodes.exchangesync.sync.SyncCalendarsImpl.syncAll(SyncCalendarsImpl.java:98)
	at com.zerodes.exchangesync.App.main(App.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.http.HTTPException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)

**Comment by PilleOnline** [comment]
My guess would be, that you are using a JDK greater than 8, which will not work out of the box (they have removed the jaxb from 9 on.

A possible solution for clients to circumvent the general problem was posted here: https://stackoverflow.com/a/43574427

**Comment by MatthiasLohr** [comment]
@gdenning, would it be possible to update that?

**Comment by fabiogermann** [comment]
@MatthiasLohr @sereeth I was faced with the same issue, the solution for me was to include the following dependency:
```diff --git a/pom.xml b/pom.xml
--- a/pom.xml
+++ b/pom.xml
@@ -21,6 +21,11 @@
        </repositories>
 
        <dependencies>
+               <dependency>
+                       <groupId>javax.xml.ws</groupId>
+                       <artifactId>jaxws-api</artifactId>
+                       <version>2.3.1</version>
+               </dependency>
                <dependency>
                        <groupId>com.microsoft.ews-java-api</groupId>
                        <artifactId>ews-java-api</artifactId>
```
hope that helps.
